//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_FlightManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public long PhoneNumber { get; set; }
        public int Experience { get; set; }
        public string IsFaculty { get; set; }
        public int Dept_id { get; set; }
    }
}
