//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_FlightManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHN32_MMS124_TESTEntities : DbContext
    {
        public CHN32_MMS124_TESTEntities()
            : base("name=CHN32_MMS124_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FMS_tbl_AirBusDetails> FMS_tbl_AirBusDetails { get; set; }
        public virtual DbSet<FMS_tbl_AirBusSeries> FMS_tbl_AirBusSeries { get; set; }
        public virtual DbSet<FMS_tbl_BonusMilesDEtails> FMS_tbl_BonusMilesDEtails { get; set; }
        public virtual DbSet<FMS_tbl_EmployeeLogin> FMS_tbl_EmployeeLogin { get; set; }
        public virtual DbSet<FMS_tbl_FlightScheduleDetails> FMS_tbl_FlightScheduleDetails { get; set; }
        public virtual DbSet<C_employee> C_employee { get; set; }
    }
}
