//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_FlightManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FMS_tbl_AirBusDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FMS_tbl_AirBusDetails()
        {
            this.FMS_tbl_FlightScheduleDetails = new HashSet<FMS_tbl_FlightScheduleDetails>();
        }

        [Display(Name = "Airbus ID")]
        public int AirBusId { get; set; }
        [Display(Name = "Flight Name")]
        [Required(ErrorMessage = "Please enter the flight name")]
        public string Name { get; set; }
        [Display(Name = "Registration Number")]
        [Required(ErrorMessage = "Please enter the registration number of the flight")]
        [RegularExpression("[V][T][-][a-zA-Z]{3}$", ErrorMessage ="Registration Number Should start with VT- and should contain 3 characters after.")]
        public string RegistrstionNumber { get; set; }
        [Display(Name = "Commencemet Date")]
        [Required(ErrorMessage = "Please enter the commencement date of the flight")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        [Display(Name = "Maufacturing Date")]
        [Required(ErrorMessage = "Please enter the manufacturig date of the flight")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        [Display(Name = "Airbus Series")]
        [Required(ErrorMessage = "Please choose an airbus series")]
        public string AirBusSeries { get; set; }
        [Display(Name = "Premium Class Seats")]
        public Nullable<int> PremiumClassSeatingCapacity { get; set; }
        [Display(Name = "First Class Seats")]
        public Nullable<int> FirstClassSeatingCapacity { get; set; }
        [Display(Name = "Economy Class Seats")]
        public Nullable<int> EconomyClassSeatingCapacity { get; set; }
        [Display(Name = "Payload Capacity")]
        public Nullable<decimal> TakeOffWeight { get; set; }
        [Display(Name = "Flight Range")]
        public Nullable<decimal> MaximumFlightRange { get; set; }
    
        public virtual FMS_tbl_AirBusSeries FMS_tbl_AirBusSeries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FMS_tbl_FlightScheduleDetails> FMS_tbl_FlightScheduleDetails { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (ManufacturingDate < DateOfCommencement)
            {
                yield return
                  new ValidationResult(errorMessage: "DateOfCommencement must be greater than ManufacturingDate",
                                       memberNames: new[] { "EndDate" });
            }
        }
    }
}
