//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_FlightManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FMS_tbl_BonusMilesDEtails
    {
        [Display(Name = "BonusMiles Id")]
        public int BonusMilesId { get; set; }
        [Display(Name = "Flight Name")]
        [Required(ErrorMessage ="Flight Schedule is required")]
        public Nullable<int> FlightScheduleId { get; set; }
        [Display(Name = "BonusMiles(MAX)")]
        [Required(ErrorMessage ="BonusMiles Required")]
        public Nullable<int> BonusMiles { get; set; }
    
        public virtual FMS_tbl_FlightScheduleDetails FMS_tbl_FlightScheduleDetails { get; set; }
    }
}
